### PR TITLE
Add totem prefix to database tables

### PR DESCRIPTION
**Pull request by a-komarev**
This PR adds `totem_` prefix to all package database tables to prevent database name collisions with other packages and application tables. This is important because such table names like `tasks` could be used in many contexts.

### CODE REVIEW

**Comment by roshangautam** [comment]
Appreciate the concern. This needs to be reflected in TotemServiceProvider's register method as well where the existence of tasks table is being changed.

**Comment by a-komarev** [comment]
Merged with master branch and fixed table name in service provider and in alter tasks migration.

**Comment by roshangautam** [comment]
Do you think it would be better to use a config variable to add a prefix to table names ? Thoughts ?

**Comment by a-komarev** [comment]
Maybe somebody will find it useful, but I don't see any profit from it.

**Comment by vonec** [comment]
even database driver can be optional and might use redis :) since you are using queues :)

**Comment by roshangautam** [comment]
I am sorry, but I am leaning towards using a config variable to override default table names rather than adding a prefix to all table. I really do appreciate your work though. Thanks for supporting.

**Pull request closed without merging**
